### ISSUE TITLE
島の名前の表示され方

### ISSUE THREAD

**Issue by kamataryo** [tilecloud/styles.tilecloud.io#7]
`tilecloud-basic` だと >= 14 で表示される。

<img width="1552" alt="Screenshot 2019-06-27 19 51 11" src="https://user-images.githubusercontent.com/6292312/60260953-b6198700-9915-11e9-8472-e6f0f2878d20.png">

<img width="1552" alt="Screenshot 2019-06-27 19 56 34" src="https://user-images.githubusercontent.com/6292312/60260954-b6198700-9915-11e9-80af-014664c62bd5.png">

Google Maps だと、島のサイズによって出し分けられているよう。男木島ならば >=12 で表示される。

**Comment by kamataryo** [comment]
フォントサイズを大きくし、もう少し小さいズームで表示するようにしてもいいかもしれない。

**Comment by miya0001** [comment]
Close in favor for now. 😊
